version: '3'
services:
  app:
    build: ./
    ports:
      - "8061:8000"
      - "9108:9000"
      - "10061:10000"
    expose:
      - 8000
      - 9000
      - 10000
    volumes:
      - ./:/app
      - /app/target
      - /app/project/project
      - /app/project/target
    container_name: pogo-api
    stdin_open: true
    tty: true
    env_file:
      - ./.env